### ISSUE TITLE
Feeds does not support cyrillic since May 11

### ISSUE THREAD

**Issue by aprilman** [leafac/kill-the-newsletter#1]
Hi. The feed does not support Cyrillic since May 11, example: https://www.kill-the-newsletter.com/feeds/p00s7ek5vsj0zfvivx0a.xml , https://www.kill-the-newsletter.com/feeds/yc6xc6n1sfna44vs44hg.xml . Please, fix it. Sorry for my english.

**Comment by leafac** [comment]
Thank you for the bug report. I deployed a fix that should apply to emails received after 2018-05-23, but foreign characters are hard to handle right, so please let me know if the issue persists.
