### ISSUE TITLE
Not receiving mails

### ISSUE THREAD

**Issue by retiolus** [leafac/kill-the-newsletter#100]
I just created 2 inboxes, I don't receive emails in neither of them...

The site I'm trying to register sends a confirmation email, and I don't receive it, so I sent mails from both tuta.io and my personal email address with my own domain and mails don't appear either...

**Comment by leafac** [comment]
Hi @retiolus,

Thanks for reaching out.

The feed you mentioned doesn’t seem to exist anymore. I don’t know what could have happened.

Can you please start over by creating a new feed?

If it still doesn’t work please reopoen the issue.

Thanks.
