### ISSUE TITLE
Database backup / server migration 

### ISSUE THREAD

**Issue by stefan-dus** [leafac/kill-the-newsletter#101]
Hello,
is it enough to just copy the binary + conmfig + the tmp folder where the application runs from? 
> /tmp/caxa/kill-the-newsletter/dxvoiiwdvh/

**Comment by leafac** [comment]
Hi @stefan-dus,

Thanks for reaching out.

All the data generated by Kill the Newsletter! is under the `data/` directory, and copying it around is enough for backups and server migration.

I recommend that you update your installation to the latest version, following the instructions on the [changelog](https://github.com/leafac/kill-the-newsletter/blob/37caf3a24bcff9d620698dafbd115feff1f0f377/CHANGELOG.md).

From then on, you may follow the [instructions from the documentation](
https://github.com/radically-straightforward/radically-straightforward/blob/aa35caf403bf46df083eaefdb3d96f86cb574941/guides/deployment.md#backup-and-migration).
