### ISSUE TITLE
--migrate wont work from 2.0.2

### ISSUE THREAD

**Issue by stefan-dus** [leafac/kill-the-newsletter#105]
In version 2.0.3 --migrate cannot be used (unknown). 
In version 2.0.2 it wont do anything besided starting the ktn server. 
Log: 

2024-06-06T07:23:41.356Z 	KILL THE NEWSLETTER! 	2.0.2 	START
2024-06-06T07:23:42.361Z 	EMAIL 	START
2024-06-06T07:23:42.480Z 	SERVER 	18000 	START

Command: ./kill-the-newsletter/kill-the-newsletter ./configuration.mjs --migrate ../kill-the-newsletter.old/data/kill-the-newsletter.db >> ./migration.txt 2>&1

In 2.0.1 it works as intended. 

Maybe include this info in the change log or keep the migration functionality in whole 2.x? 

Thanks for your work, Leandro!

**Comment by leafac** [comment]
Thanks for the report. I added a note to the changelog.
