### ISSUE TITLE
Feed setting icon non-working

### ISSUE THREAD

**Issue by iago-pssjd** [leafac/kill-the-newsletter#110]
I subscribed to two different feeds through Kill the Newsletter and for both I updated the feed settings icon with the corresponding icons, however I see the same icon for both feeds. Is it expected?

Thanks!

**Comment by leafac** [comment]
Hi @iago-pssjd,

Thanks for reaching out.

I think that maybe you created one inbox in Kill the Newsletter! and subscribed to two newsletters with it. If that’s the case, then it explains why you’d see the same icon for the two feeds: The icon is associated with the Kill the Newsletter! inbox.

I recommend that you create one Kill the Newsletter! inbox for each newsletter that you subscribe to. Not only will the icons look right, but also a newsletter publisher won’t be able to manage your other subscriptions.
