### ISSUE TITLE
HTML Pages all 404

### ISSUE THREAD

**Issue by SenorFusion** [leafac/kill-the-newsletter#39]
Starting today, all of the HTML pages of my Kill The Newsletter Feeds are 404ing.

I typically open several newsletters in browser because they don't style well in my RSS reader.

`https://kill-the-newsletter.com/alternate/<page-key>.html`

This is happening on all of my feeds, not just one

Thanks!

**Comment by leafac** [comment]
Hi @SenorFusion,

Thanks for reaching out with the issue report.

The links should be `https://kill-the-newsletter.com/alternates/<page-key>.html`, not `https://kill-the-newsletter.com/alternate/<page-key>.html` (note the `s` in `alternates`). Can you please try those and see if they work for you?

I double-checked just now and the links Atom feed are correct (they’re the `<link rel="alternate" ... />` under each `<entry>`). From where did you get the wrong links?

**Comment by SenorFusion** [comment]
@leafac  Yes, I see what you mean. This may turn out to be a problem with my RSS reader.

-Fedora 30
-Liferea 1.13.5

What I've found:

-You are correct, the raw XML is providing the feed URL correctly.
-Somehow the headline (link to post) is getting converted to this format (I was incorrect in my OP):
`https://kill-the-newsletter.com/alternate/<feed-key>/<page-key>.html`

When I manually change that link to `https://kill-the-newsletter.com/alternates/<page-key>.html` it works fine.

It seems to be constructing an incorrect URL for the headline link based on what is in the feed.

Example shown in the pictures.

![alternate-links](https://user-images.githubusercontent.com/1929777/111489357-6cd42100-8710-11eb-9d5b-03f213bcde53.png)
![alternate-404](https://user-images.githubusercontent.com/1929777/111489359-6cd42100-8710-11eb-8d19-812f613d6255.png)

**Comment by SenorFusion** [comment]
Upon further review, it seems like maybe the feedreader is expecting a URL in the `<id>` field and, not finding one, tries to construct one based on the feed URL combined with the item key:

 `<id>urn:kill-the-newsletter:<page-key></id>`

**Comment by leafac** [comment]
No, the problem is that I deployed a new version of Kill the Newsletter! two days ago in which I changed the URLs. You feed reader is going off of a stale cache. It won’t be an issue for new entries coming up…

Mystery solved; I’m closing the issue for now. Let me know if it’s a problem with new entries.

And thanks for using Kill the Newsletter! 🙌
