### ISSUE TITLE
Result page should encode result in an URL parameter.

### ISSUE THREAD

**Issue by jtagcat** [leafac/kill-the-newsletter#40]
Reproduce:
1. Subscribe to a newsletter via the address.
2. Close the browser.
3. Open the browser.
4. Attempt to add the feed.
5. The feed is not there.

**Comment by leafac** [comment]
Thanks for reaching out!

I’m sorry but I’m not sure that I understand the issue. Here’s how the normal operation of Kill the Newsletter! usually goes:

1. You subscribe to a newsletter with the email address provided by Kill the Newsletter!
2. You subscribe to the Atom feed provided by Kill the Newsletter!
3. Every email sent to the email address turns up as an entry in the feed.

Are you following these steps?

Also:

1. What do you mean by the “result page”?
2. What do you mean by “result” when you say “encode result”?
3. How would said “result” be encoded in an URL parameter?

Thanks for the clarifications.

**Comment by jtagcat** [comment]
Result page looks like this:
![image](https://user-images.githubusercontent.com/38327267/121924629-9e6a8180-cd2b-11eb-9019-8d82d10c7770.png)

The URL would change to `https://kill-the-newsletter.com/#wcdewb45j1vc9w2l` or similar. (encoded in URL). More proper encoding woul be `https://kill-the-newsletter.com/?inbox=wcdewb45j1vc9w2l`

1. You subscribe to a newsletter with the email address provided by Kill the Newsletter!
2. Tab crashes / browser closed / kernel panic / out of battery / mobile devices just refresh the page
3. You subscribe to the Atom feed provided by Kill the Newsletter?
4. Nowhere to copy the feed URL from.

**Comment by leafac** [comment]
Hmmm, I’m starting to understand. But how would the user get back to the right URL? Browser history?

This seems very unlikely to happen, and even more unlikely for users to figure that they may use the browser history to fix it. Isn’t it better for them to just create another inbox and sign up for the newsletter again?

**Comment by jtagcat** [comment]
Browser history, or even page refresh.

It's an edge case, sure. Don't know whether you want to leave it as wontfix, or spend the time.

> Isn’t it better for them to just create another inbox and sign up for the newsletter again?

It's not better, it's a workaround. It's a bit annoying, but yes, I've done it.

**Comment by leafac** [comment]
Thanks for the well-thought suggestion, but I don’t think it’s right for the project right now. The random characters in the email address & feed act as a kind of password and I think it’s a bad idea to have that laying around in the browser history to work around a somewhat unusual edge case. I believe the losses outweigh the gains.

That said, I want to reiterate that I appreciate the conversation, and if I’m missing something please follow up. I hope to see you contributing to Kill the Newsletter! again in the future.
