### ISSUE TITLE
5.7.1 <address@host.com>: Relay access denied

### ISSUE THREAD

**Issue by Zeduro** [leafac/kill-the-newsletter#51]
I'm getting the following error when attempting to send emails to my Kill-the-Newsletter instance.

I followed the guide pretty meticulously, could there be something I overlooked?

DNS Records are as detailed in your guidance material.

I appreciate the work you do.

Thank you,
Eduardo

**Comment by Zeduro** [comment]
Resolved.

**Comment by leafac** [comment]
Oh, great! What was the issue?
