### ISSUE TITLE
Cannot execute binary file

### ISSUE THREAD

**Issue by elonj** [leafac/kill-the-newsletter#55]
I am trying to use kill-the-newsletter on Oracle Linux 8. It is aarch64. When I run "[the server] # ./kill-the-newsletter configuration.js" per the instruction. There is a warning: "./kill-the-newsletter: ./kill-the-newsletter: cannot execute binary file". I used kill-the-newsletter--linux--v1.0.1.tgz.
Is that aarch64 not supported? Can you provide some suggestion?

Thank you in advance.

**Comment by elonj** [comment]
Get in work in Ubuntu x86_64. Thanks

**Comment by leafac** [comment]
Thanks for reaching out. ARM support for Kill the Newsletter! is coming soon, given that [caxa](https://github.com/leafac/caxa) now supports it.
