### ISSUE TITLE
separate email and feed id

### ISSUE THREAD

**Issue by tcurdt** [leafac/kill-the-newsletter#75]
A very cool project. There is one thing I would highly recommend to change though:
Don't use the same id on the inbox and the feed.

Otherwise any owner of an email newsletter can easily see what other feeds you are reading.

```
<ID>@kill-the-newsletter.com
Copy
Subscribe to the Atom feed at
https://kill-the-newsletter.com/feeds/<ID>.xml
```

**Comment by leafac** [comment]
Hi @tcurdt,

Thanks for reaching out.

The idea is that you’ll create one inbox per newsletter. This allows you to give the feeds different titles and organize them in the feed reader more easily.

Perhaps we could introduce a layer of indirection between the ids of the email address and the Atom feed address, as you mention, but I think that the benefit would be negligible. And, naturally, it would only apply to new inboxes, given that we can’t break existing inboxes.
