### ISSUE TITLE
kill the newsletter doesnt work for monring brew

### ISSUE THREAD

**Issue by fislysandi** [leafac/kill-the-newsletter#76]
i want to simply tell that kill the newsletter doesnt work with Morningbrew how can i fix that?

**Comment by leafac** [comment]
Hi @fislysandi,

Thanks for reaching out. Can you please give more details? What exactly did you try? What goes wrong? What error messages do you see, if any?

Thanks.

**Comment by ajatoledo** [comment]
@fislysandi, not sure if you're running your own instance. However, in my own experience, I've found many daily newsletters like _Morning Brew_ remove subscribers quickly if they encounter any delivery issues. A few weeks back, my instance went down for two days. Once I had it back online, most of my newsletters returned, except _Morning Brew_. I had to create a new feed and re-subscribe to _Morning Brew_; once I did, it worked as expected.

**Comment by leafac** [comment]
@ajatoledo Interesting. Thanks for the information. It’s odd that they’re doing this. Email delivery standards recommends that the sender retries for 4/5 days before giving up. Even then, they’re being eager to remove you from subsequent deliveries 🤷

I’ll close the issue for the time being. If you find that it needs further work, please reopen it.
