### ISSUE TITLE
conten are encoded in "content" tag

### ISSUE THREAD

**Issue by huangyg11** [leafac/kill-the-newsletter#8]
I used to forward stackoverflow newsletter to kill-the-newsletter and subscribe with tiny tiny rss. 

Before January 29, 2019, I got the newsletter in tt-rss normally, but the next letter received in February 12, 2019 break. I find the content is encoded in "content" tag, cause tt-rss to display it as blank. 

Is this intended or is this a bug?

**Comment by huangyg11** [comment]
I find it is because tt-rss don't support html content type

**Comment by leafac** [comment]
You can check your feed at https://validator.w3.org/feed/

If the validation passes, the problem is your reader (for example, tt-rss); otherwise the problem is in **Kill the Newsletter!** and we can investigate.
