### ISSUE TITLE
Unable to validate your email domain

### ISSUE THREAD

**Issue by RandmTask** [leafac/kill-the-newsletter#83]
I get this email when trying to sign up at [Recomendo](https://www.recomendo.com/):
**Please enter a valid email
We were unable to validate your email domain**

Any workarounds for these type of websites?

**Comment by CeleritasCelery** [comment]
About this same time I stopped getting emails from all my substack subscriptions. Trying to sign up again with kill-the-newsletter led to the same error @RandmTask showed. It looks like substack already has an [rss feed](https://support.substack.com/hc/en-us/articles/360038239391-Is-there-an-RSS-feed-for-my-publication-), so I can switch to that, but wanted to report that I have seen this issue too.

**Comment by leafac** [comment]
Hi y’all,

Yes, unfortunately some newsletter publishers blocklist Kill the Newsletter! I wrote a paragraph about this in the [new version](https://kill-the-newsletter.com/) under the “Why can’t I subscribe to a newsletter with my Kill the Newsletter! email?” section.
