### ISSUE TITLE
Subscription confirmation type "Reply to email"

### ISSUE THREAD

**Issue by JMskch** [leafac/kill-the-newsletter#89]
Hi, I subscribed to one newsletter, which requests confirmation by replying specific text to that email.

Text from email: "Reply 'AI' to this email, so we know you're human."

Is there some solution to this or is this somehow solvable?

KR, JM

**Comment by ManuelFte** [comment]
It's funny how we came here looking to subscribe to the same newsletter, hahahaha.

What an annoying requirement, wanting to get into our emails one way or another. 😒

Emails are so archaic and so uncomfortable for this purpose. If I can't read the newsletter on my feed reader then I'm just not subscribing. I don't want my inbox to be spammed, and I won't read the newsletter there even if I try. We're looking to read it as a feed _because we want to read it_. F to the maker of that newsletter.

**Comment by tomw1808** [comment]
I don't know if that helps somehow, but I made it work by subscribing to the newsletter with my regular gmail email and then forwarding that through filters through gmail https://knowledge.workspace.google.com/kb/gmail-automatic-forwarding-000009025

**Comment by leafac** [comment]
Hi y’all 👋

As you pointed out, unfortunately Kill the Newsletter! doesn’t support this scenario because we don’t want to get in the business of **sending** emails and having to control spam—**receiving** email is much easier in comparison.

The workaround of signing up with your real email, then filtering and forwarding seems to be a popular one 🤗

Best.

**Comment by EasternPA** [comment]
> Hi, I subscribed to one newsletter, which requests confirmation by replying specific text to that email.
> 
> Text from email: "Reply 'AI' to this email, so we know you're human."
> 
> Is there some solution to this or is this somehow solvable?
> 
> KR, JM

Commenting on an old topic here, but I front my KtN emails with duckduckgo email protection. So I setup a DDG email forwarding account to my Gmail. Then complete the signup. Then change the forwarding address in DDG to my KtN input email.

That's a way to interact via email before shunting it off to KtN as originally planned.
