### ISSUE TITLE
Unable to parse any XML input. Error on line 232: An invalid XML character (Unicode: 0xb) was found in the element content of the document.

### ISSUE THREAD

**Issue by conrad784** [leafac/kill-the-newsletter#9]
First of all, thank you for this service!

Unfortunately it does sometimes generate bad XML, I put the anonymized feed into a 
[validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcsachweh.de%2Fshare%2Ftest.xml)

If you need it, I can provide the actual link via mail.

**Comment by leafac** [comment]
Thanks for catching that. Feed created from now on shouldn’t run into that issue.
