### ISSUE TITLE
Suggestion for improvement

### ISSUE THREAD

**Issue by jbionic2016** [leafac/kill-the-newsletter#95]
Hi there,

Thanks for your service.

There are some visible limitations of your service. I think the problem I touch below could be solved if you allow displaying the very first note to reach the new virtual email address right in the screen that shows it.

The problem is as follows
I am signed up for a few forum threads in order to get notified of updates on my email. I want to generate from those email notifications new RSS feeds in order to read them via Feedly.

I've tried to use kill-the-newsletter.com, which creates a virtual email address and links it to a certain RSS, which I can then upload to Feedly.

At the same time I've also tried to set up filtered email forwarding from my main email box to the virtual address created by kill-the-newsletter.com.

The problem is that in order to initiate email forwarding my email provider first sends a note with a code to the virtual email address. I am supposed to confirm forwarding by validating the code in my main email box. 

I expected that the note with the code would reach me via RSS feed in Feedly. However Feedly is processing new feeds real slow, so the note with the code never reaches me.

Thanks.

![111](https://github.com/leafac/kill-the-newsletter/assets/23212486/7b6e2746-ff99-400f-8dd1-5e68c32941c5)

**Comment by leafac** [comment]
Hi @jbionic2016,

Thanks for reaching out.

That’s an interesting idea.

I didn’t know that Feedly was slow to update. Is it like that all the time, or just that one time?

I think that most feed readers fetch the feed when you subscribe to it, and by then you’d already have subcribed to the newsletter and the publisher would have sent the email confirmation link 🤔

In any case, in situations like this I prefer to wait for more people to report that they’d like a feature before jumping to it. I’ll close the issue for now and reopen if necessary.

Best.
