### ISSUE TITLE
Is this possible? A list requires me to send an email to sign up

### ISSUE THREAD

**Issue by shawnhooper** [leafac/kill-the-newsletter#97]
Can you use Kiill the Newsletter with mailing lists that registration is done via email?

**Comment by saeedesmaili** [comment]
Yeah, when you subscribe to the feed with your RSS reader, you'll get the confirmation email in the feed and will be able to click on the link to confirm.

**Comment by leafac** [comment]
Hi @shawnhooper,

Thanks for reaching out.

I added [a section explaining](https://kill-the-newsletter.com/) just that:  “How do I confirm my newsletter subscription?”

Best.
